DROP TABLE IF EXISTS CLAIM;
DROP TABLE IF EXISTS CLAIM_HEAD;
CREATE TABLE CLAIM (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  claim_reference VARCHAR(250) NOT NULL,
  incident_date VARCHAR(250) NOT NULL,
  name VARCHAR(250) DEFAULT '',
  detail VARCHAR(250) DEFAULT '',
  insurer VARCHAR(250) DEFAULT '',
  state VARCHAR(250) DEFAULT ''
);

CREATE TABLE CLAIM_HEAD (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  cost VARCHAR(250) DEFAULT '',
  detail VARCHAR(250) DEFAULT '',
  state VARCHAR(250) DEFAULT ''
);