DROP TABLE IF EXISTS CLAIM;
DROP TABLE IF EXISTS HEAD_CLAIM;
CREATE TABLE CLAIM (
  claim_id INT AUTO_INCREMENT  PRIMARY KEY,
  claim_reference VARCHAR(250) NOT NULL,
  incident_date VARCHAR(250) NOT NULL,
  claimant_name VARCHAR(250) DEFAULT '',
  claimant_detail VARCHAR(250) DEFAULT '',
  insurer VARCHAR(250) DEFAULT '',
  state VARCHAR(250) DEFAULT ''
);

CREATE TABLE HEAD_CLAIM (
  head_claim_id INT AUTO_INCREMENT  PRIMARY KEY,
  claim_id INT,
  cost VARCHAR(250) DEFAULT '',
  detail VARCHAR(250) DEFAULT '',
  state VARCHAR(250) DEFAULT ''
);