DROP TABLE IF EXISTS CLAIM;

CREATE TABLE CLAIM (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  claim_reference VARCHAR(250) NOT NULL,
  incident_date VARCHAR(250) NOT NULL,
  name VARCHAR(250) DEFAULT '',
  insurer VARCHAR(250) DEFAULT '',
  state VARCHAR(250) DEFAULT ''
);